version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/iot_food_04
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Quocviet2003@

  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=iot_food_04
      - MYSQL_ROOT_PASSWORD=Quocviet2003@
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data:
